// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSjzHWyzJaYL-tu2VUS0e_OQXceiiL0h0',
    appId: '1:527445487310:web:b4ba7859bc4eafa2606a9f',
    messagingSenderId: '527445487310',
    projectId: 'ccaa-3e80a',
    authDomain: 'ccaa-3e80a.firebaseapp.com',
    storageBucket: 'ccaa-3e80a.appspot.com',
    measurementId: 'G-EZMM86E887',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5VVN0fA85cfLmzq6JCKrJxezRzAGvhVE',
    appId: '1:527445487310:android:04ab8d89d1ffbc8c606a9f',
    messagingSenderId: '527445487310',
    projectId: 'ccaa-3e80a',
    storageBucket: 'ccaa-3e80a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9PrIYyg8Pe67rBQErFxYAhudR4nVDX4M',
    appId: '1:527445487310:ios:15dfc9a2b455624d606a9f',
    messagingSenderId: '527445487310',
    projectId: 'ccaa-3e80a',
    storageBucket: 'ccaa-3e80a.appspot.com',
    iosBundleId: 'com.example.test1',
  );
}
